services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    command: sh -c "/auction"
    depends_on:
      - mongo
    environment:
      - BATCH_INSERT_INTERVAL=20s
      - MAX_BATCH_SIZE=4
      - AUCTION_INTERVAL=20s
      - MONGODB_URL=mongodb://admin:admin@mongo:27017/auctions?authSource=admin
      - MONGODB_DB=auctions
    ports:
      - 8080:8080

  mongo:
    image: mongo:7
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
